---

- name: delete local charts from /tmp/sdcore-helm-charts/
  file:
    path: /tmp/sdcore-helm-charts/
    state: absent
  when: inventory_hostname in groups['master_nodes']  and core.helm.local_charts
  ignore_errors: yes

- name: remove iosmcn core
  kubernetes.core.helm:
    name: sd-core
    release_namespace: ios-mcn
    state: absent
    wait: true
  when: inventory_hostname in groups['master_nodes']
  ignore_errors: yes

- name: remove 5gc chart repo
  kubernetes.core.helm_repository:
    name: aether
    state: absent
    repo_url: "https://charts.aetherproject.org"
  when: inventory_hostname in groups['master_nodes']
  ignore_errors: yes

- name: remove cord chart repo
  kubernetes.core.helm_repository:
    name: cord
    state: absent
    repo_url: "https://charts.opencord.org"
  when: inventory_hostname in groups['master_nodes']
  ignore_errors: yes

- name: waiting for ios-mcn pods to terminate
  shell: |
    kubectl wait -n ios-mcn --for=delete --all=true -l app!=ue pod --timeout=180s
  when: inventory_hostname in groups['master_nodes']
  ignore_errors: yes

- name: delete namespace ios-mcn
  shell: |
    kubectl delete namespace ios-mcn
  when: inventory_hostname in groups['master_nodes']
  ignore_errors: yes

